// src/App.tsx
import Navbar from "core/Navbar/Navbar";
import { BrowserRouter } from "react-router-dom";
import "./App.scss";
import RoutesApp from "./routes";

function App() {
  return (
    <section className='main-container'>
      <BrowserRouter>
        <Navbar />
        <main>
          <RoutesApp></RoutesApp>
        </main>
      </BrowserRouter>
    </section>
  );
}

export default App;

// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'green-wallet';
}

<section class="container flex">
  <app-nav-bar></app-nav-bar>
  <main class="p-3">
    <div class="grid">
      <div class="col-12">
        <router-outlet></router-outlet>
      </div>
    </div>
  </main>
</section>
